#########################
# project configuration #
#########################
# C++ project, but if we specify it, travis overites our CXX ENV variables
language: generic
dist: trusty
sudo: false

before_install:
  # Install a recent CMake
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.12/cmake-3.12.1-Linux-x86_64.tar.gz"
      echo "pulling down cmake" ${CMAKE_URL}  
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${TRAVIS_BUILD_DIR}/cmake/bin:${PATH}
      echo ${TRAVIS_BUILD_DIR}/cmake/bin
      ls ${TRAVIS_BUILD_DIR}/cmake/bin
      export CMAKE=$TRAVIS_BUILD_DIR/cmake/bin/cmake
      echo cool
    else
      brew upgrade cmake || brew install cmake
      export CMAKE=cmake
    fi
  - cmake --version
  
   # Set env vars for C++ on mac
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
        export CXX=g++
        export CC=gcc
    fi

################
# build matrix #
################
matrix:
  include:
    # OSX / Clang
    - os: osx
      env: CACHE_NAME=JOB0
      osx_image: xcode9.4
    # Linux / GCC
    - os: linux
      env: COMPILER_NAME=gcc COMPILER==g++-7 CXX==g++-7 CCgcc-7 CACHE_NAME=JOB1
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
    # Linux / Clang
    - os: linux
      env: COMPILER_NAME=clang CXX=clang++-5.0 CC=clang-5.0 LLVM_VERSION=5.0 CACHE_NAME=JOB2
      addons:
      apt:
        sources:
          - llvm-toolchain-trusty-5.0
        packages:
          - clang-5.0

################
# build script #
################

script:
  # show OS/compiler version
  - uname -a
  - $CXX --version
  - $CMAKE --version

  # compile and execute 
  - git submodule update --init --recursive
  - mkdir -p build && cd build
  - $CMAKE .. -DGPUVIS_build_tests=ON
  - $CMAKE --build . --target package --config Release -- -j4
  - cd bin && .\Unit_Tests_run --gtest_output=xml:tests.xml